<?php

namespace Magestio\Whatsapp\Block;

use Magento\Framework\Url\EncoderInterface;
use Magento\Framework\View\Element\Template;

use Magento\Framework\View\Element\Template\Context;
use Magento\Store\Model\StoreManagerInterface;
use Magestio\Whatsapp\Model\ConfigInterface;

class Whatsapp extends Template
{

    /**
     * @var StoreManagerInterface
     */
    private $storeManager;

    /**
     * @var EncoderInterface
     */
    private $encoder;

    /**
     * Whatsapp constructor.
     * @param StoreManagerInterface $storeManager
     * @param Context $context
     * @param array $data
     * @param EncoderInterface $encoder
     */
    public function __construct(
        StoreManagerInterface $storeManager,
        Context $context,
        EncoderInterface $encoder,
        array $data = []
    ) {
        $this->encoder = $encoder;
        $this->storeManager = $storeManager;
        parent::__construct($context, $data);
    }

    public function _toHtml()
    {
        if($this->_scopeConfig->getValue(ConfigInterface::XML_PATH_WHATSAPP_ACTIVE) == 0)
            return false;
        else
            return parent::_toHtml(); // TODO: Change the autogenerated stub
    }

    public function getTelephone(){
        return $this->_scopeConfig->getValue(ConfigInterface::XML_PATH_WHATSAPP_PHONE);
    }

    public function getText(){
        $html = __('Support on URL: %1  %0D%0A ---- %0D%0A Write your question below.',$this->getCurrentUrl());
        return $html;
    }
    /**
     * Return Current url
     * @return string
     */
    protected function getCurrentUrl() {
        return $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
    }

}